# Generated by Django 5.2.8 on 2025-11-22 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='roastresult',
            new_name='core_roastr_task_id_5be9a0_idx',
            old_name='core_roastr_task_id_idx',
        ),
        migrations.RenameIndex(
            model_name='roastresult',
            new_name='core_roastr_status_ffe3cc_idx',
            old_name='core_roastr_status_created_idx',
        ),
    ]
